Client testing now stops when a client fails

diff --git a/src/librosie/Makefile b/src/librosie/Makefile
--- a/src/librosie/Makefile
+++ b/src/librosie/Makefile
@@ -153,7 +153,12 @@ test:
 	exit 1; \
 	fi; \
 	here="$(shell pwd)"; \
-	for client in $(clients); do cd $${here}/$$client && $(MAKE) test; done
+	for client in $(clients); \
+	do cd $${here}/$$client && $(MAKE) test; \
+	if [ $$? -ne 0 ]; then \
+		echo "TEST FAILED: $$client"; exit -1; \
+		fi; \
+	done
 
 installtest:
 	@here="$(shell pwd)"; \
